// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPark.Data.Context;

#nullable disable

namespace UPark.Migrations.Migrations
{
    [DbContext(typeof(UParkDbContext))]
    [Migration("20260418194934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("UPark.Data.Models.Espacio", b =>
                {
                    b.Property<int>("IdEspacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEstacionamiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEspacio");

                    b.HasIndex("IdEstacionamiento");

                    b.ToTable("Espacios");
                });

            modelBuilder.Entity("UPark.Data.Models.Estacionamiento", b =>
                {
                    b.Property<int>("IdEstacionamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdEstacionamiento");

                    b.ToTable("Estacionamientos");

                    b.HasData(
                        new
                        {
                            IdEstacionamiento = 1,
                            CapacidadTotal = 50,
                            Nombre = "IMM",
                            Ubicacion = "Frente a la Universidad"
                        },
                        new
                        {
                            IdEstacionamiento = 2,
                            CapacidadTotal = 40,
                            Nombre = "UMAD",
                            Ubicacion = "Detrás de la Universidad"
                        });
                });

            modelBuilder.Entity("UPark.Data.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("Matricula");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("UPark.Data.Models.Usuario", b =>
                {
                    b.Property<string>("Matricula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Matricula");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UPark.Data.Models.Espacio", b =>
                {
                    b.HasOne("UPark.Data.Models.Estacionamiento", "Estacionamiento")
                        .WithMany("Espacios")
                        .HasForeignKey("IdEstacionamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("UPark.Data.Models.Notificacion", b =>
                {
                    b.HasOne("UPark.Data.Models.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("Matricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UPark.Data.Models.Estacionamiento", b =>
                {
                    b.Navigation("Espacios");
                });

            modelBuilder.Entity("UPark.Data.Models.Usuario", b =>
                {
                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
